{
 "title": "connectors",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "connect_cluster",
    "label": "connect cluster",
    "query": {
     "query": "label_values(kafka_connect_start_time_seconds{alias=\"acdc/\"}, k8s_app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connector Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"})"
    }
   ]
  },
  {
   "title": "Connector Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kafka_connect_worker_connector_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"}) by (k8s_app)",
     "legendFormat": "{{ k8s_app }}"
    }
   ]
  },
  {
   "title": "Task Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_task_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"})"
    }
   ]
  },
  {
   "title": "Task Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kafka_connect_worker_task_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"}) by (k8s_app) ",
     "legendFormat": "{{ k8s_app }}"
    }
   ]
  },
  {
   "title": "Task Status Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_connect_worker_connector_running_task_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_worker_connector_paused_task_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum (kafka_connect_worker_connector_destroyed_task_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum (kafka_connect_worker_connector_failed_task_count{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"})",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_status{alias=\"acdc/\", status=\"failed\", k8s_app=~\"${connect_cluster}\"}"
    }
   ]
  },
  {
   "title": "Busy Source Tasks Top 10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum (irate(kafka_connect_source_task_source_record_poll_total{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"}[5m])) by (connector))",
     "legendFormat": "{{ connector }}"
    }
   ]
  },
  {
   "title": "Busy Sink Tasks Top 10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "topk(10, sum (irate(kafka_connect_sink_task_sink_record_read_total{alias=\"acdc/\", k8s_app=~\"${connect_cluster}\"}[5m])) by (connector))",
     "legendFormat": "{{ connector }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}