{
 "title": "connection for user",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source_connector_name",
    "query": {
     "query": "label_values(kafka_connect_connector_status{alias=\"acdc/\", connector=~\"source.*\"}, connector)"
    }
   },
   {
    "name": "sink_connector_name",
    "query": {
     "query": "label_values(kafka_connect_connector_status{alias=\"acdc/\", connector=~\"sink.*\"}, connector)"
    }
   },
   { "name": "alias", "query": "acdc/" }
  ]
 },
 "panels": [
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent(kafka_connect_connector_status{alias=\"acdc/\", connector = \"$source_connector_name\"})"
    },
    {
     "expr": "absent(kafka_connect_connector_status{alias=\"acdc/\", connector = \"$sink_connector_name\"})"
    }
   ]
  },
  {
   "title": "Lag Now",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_consumer_fetch_manager_records_lag{alias=\"acdc/\", clientId=~\"connector-consumer-${sink_connector_name}.*\"} >= 0)"
    }
   ]
  },
  {
   "title": "Task Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{alias=\"acdc/\", connector = \"$sink_connector_name\"})"
    }
   ]
  },
  {
   "title": "Task Status Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_status{alias=\"acdc/\", connector=\"$sink_connector_name\"} * on(task) group_left kafka_connect_sink_task_partition_count{alias=\"acdc/\", connector=\"$sink_connector_name\"}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " kafka_consumer_fetch_manager_records_lag{alias=\"acdc/\", clientId=~\"connector-consumer-${sink_connector_name}.*\"}",
     "legendFormat": "partition: {{ partition }}"
    }
   ]
  },
  {
   "title": "Record Consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_connect_sink_task_sink_record_send_total{alias=\"acdc/\", connector=\"${sink_connector_name}\"}[5m])",
     "legendFormat": "task-{{ task }}"
    }
   ]
  },
  {
   "title": "Task Put Batch Max Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_max_time_ms{alias=\"acdc/\", connector=\"${sink_connector_name}\"}",
     "legendFormat": "task-{{ task }}"
    }
   ]
  },
  {
   "title": "Record Active Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_sink_record_active_count{alias=\"acdc/\", connector=\"${sink_connector_name}\"}",
     "legendFormat": "task-{{ task }}"
    }
   ]
  }
 ]
}