let DataSystemResourceTypeConstant = {
  MYSQL_CLUSTER: 'MYSQL_CLUSTER',
  MYSQL_INSTANCE: 'MYSQL_INSTANCE',
  MYSQL_DATABASE: 'MYSQL_DATABASE',
  MYSQL_TABLE: 'MYSQL_TABLE',

  TIDB_CLUSTER: 'TIDB_CLUSTER',
  TIDB_SERVER: 'TIDB_SERVER',
  TIDB_DATABASE: 'TIDB_DATABASE',
  TIDB_TABLE: 'TIDB_TABLE',

  KAFKA_CLUSTER: 'KAFKA_CLUSTER',
  KAFKA_TOPIC: 'KAFKA_TOPIC',


  HIVE: 'HIVE',
  HIVE_DATABASE: 'HIVE_DATABASE',
  HIVE_TABLE: 'HIVE_TABLE',
}

export {
  DataSystemResourceTypeConstant,
}
