let DataSystemResourceTypeConstant = {
  MYSQL_CLUSTER: 'MYSQL_CLUSTER',
  MYSQL_INSTANCE: 'MYSQL_INSTANCE',
  MYSQL_DATABASE: 'MYSQL_DATABASE',
  MYSQL_TABLE: 'MYSQL_TABLE',

  TIDB_CLUSTER: 'TIDB_CLUSTER',
  TIDB_SERVER: 'TIDB_SERVER',
  TIDB_DATABASE: 'TIDB_DATABASE',
  TIDB_TABLE: 'TIDB_TABLE',

  KAFKA_CLUSTER: 'KAFKA_CLUSTER',
  KAFKA_TOPIC: 'KAFKA_TOPIC',


  HIVE: 'HIVE',
  HIVE_DATABASE: 'HIVE_DATABASE',
  HIVE_TABLE: 'HIVE_TABLE',

  ELASTICSEARCH_CLUSTER: 'ELASTICSEARCH_CLUSTER',
  ELASTICSEARCH_INDEX: 'ELASTICSEARCH_INDEX',

  STARROCKS_CLUSTER: 'STARROCKS_CLUSTER',
  STARROCKS_FRONTEND: 'STARROCKS_FRONTEND',
  STARROCKS_DATABASE: 'STARROCKS_DATABASE',
  STARROCKS_TABLE: 'STARROCKS_TABLE',
}

export {
  DataSystemResourceTypeConstant,
}
