spring:
  profiles:
    active: @profile.active@
  application:
    name: acdc-devops-backend-controller
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    properties:
      hibernate.jdbc.time_zone: GMT+8
  liquibase:
    contexts: @liquibase.context@

server:
  port: 8080

scheduler:
  config:
    pool-size: 24
  user-trigger:
    interval:
      ms: 10000
  watch-cluster:
    interval:
      ms: 10000
  extend-event:
    interval:
      ms: 10000

# metrics:
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
