{
 "title": "connection for operation",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source_connector_name",
    "query": {
     "query": "label_values(kafka_connect_connector_status{alias=\"acdc/\", connector=~\"source.*\"}, connector)"
    }
   },
   {
    "name": "sink_connector_name",
    "query": {
     "query": "label_values(kafka_connect_connector_status{alias=\"acdc/\", connector=~\"sink.*\"}, connector)"
    }
   },
   { "name": "alias", "query": "acdc/" },
   {
    "name": "connect_worker_pod_names",
    "query": {
     "query": "label_values(kafka_connect_connector_status{connector=~\"${source_connector_name}|${sink_connector_name}\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Source Task Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{connector = \"$source_connector_name\"})"
    }
   ]
  },
  {
   "title": "Sink Task Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{connector = \"$sink_connector_name\"})"
    }
   ]
  },
  {
   "title": "Lag Now",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_consumer_fetch_manager_records_lag{clientId=~\"connector-consumer-${sink_connector_name}.*\"} >= 0)"
    }
   ]
  },
  {
   "title": "Task Status Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_status{connector = \"$sink_connector_name\"} * on(task) group_left kafka_connect_sink_task_partition_count{connector = \"$sink_connector_name\"}"
    },
    {
     "expr": "kafka_connect_connector_task_status{connector = \"$source_connector_name\"}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " kafka_consumer_fetch_manager_records_lag{alias=\"acdc/\", clientId=~\"connector-consumer-${sink_connector_name}.*\"}",
     "legendFormat": "partition: {{ partition }}"
    }
   ]
  },
  {
   "title": "Record Produced/Consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_connect_sink_task_sink_record_send_total{connector=\"${sink_connector_name}\"}[5m])",
     "legendFormat": "sink-task-{{ task }}"
    },
    {
     "expr": "rate(kafka_connect_source_task_source_record_write_total{connector=\"${source_connector_name}\"}[5m])",
     "legendFormat": "source-task-{{ task }}"
    }
   ]
  },
  {
   "title": "Task Poll/Put Batch Max Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms{alias=\"${alias}\", connector=\"${source_connector_name}\"}",
     "legendFormat": "source-task-{{ task }}"
    },
    {
     "expr": "kafka_connect_sink_task_put_batch_max_time_ms{alias=\"${alias}\", connector=\"${sink_connector_name}\"}",
     "legendFormat": "sink-task-{{ task }}"
    }
   ]
  },
  {
   "title": "Memory Usage Of Connect Worker ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{alias=\"${alias}\", kubernetes_pod_name=~\"${connect_worker_pod_names}\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Pool Usage Of Connect Worker ",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{alias=\"${alias}\", kubernetes_pod_name=~\"${connect_worker_pod_names}\"}",
     "legendFormat": "{{ kubernetes_pod_name }}-{{ pool }}"
    }
   ]
  },
  {
   "title": "GC Times Of Connect Worker ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{alias=\"${alias}\", kubernetes_pod_name=~\"${connect_worker_pod_names}\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}-{{ gc }}"
    }
   ]
  },
  {
   "title": "CPU Usage Of Connect Worker ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{kubernetes_pod_name=~\"${connect_worker_pod_names}\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Thread Of Connect Worker ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{alias=\"${alias}\", kubernetes_pod_name=~\"${connect_worker_pod_names}\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}