{
 "title": "mysql source connector",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source_connector_name",
    "query": {
     "query": "label_values(kafka_connect_connector_status{alias=\"acdc/\", connector=~\"source-mysql.*\"}, connector)"
    }
   },
   { "name": "alias", "query": "acdc/" }
  ]
 },
 "panels": [
  {
   "title": "DB Connect Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_connected{alias=\"${alias}\", name=\"${source_connector_name}\"}"
    }
   ]
  },
  {
   "title": "Binlog Position",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_binlogposition{alias=\"${alias}\", name=\"${source_connector_name}\"}"
    }
   ]
  },
  {
   "title": "Gtid Enable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_isgtidmodeenabled{alias=\"${alias}\", name=\"${source_connector_name}\"}"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_millisecondsbehindsource{alias=\"${alias}\", name=\"${source_connector_name}\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Event Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\", alias=\"${alias}\", name=\"${source_connector_name}\"}",
     "legendFormat": "total event"
    }
   ]
  },
  {
   "title": "Schema Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(debezium_metrics_changesapplied{alias=\"${alias}\", name=\"${source_connector_name}\"}[5m])"
    }
   ]
  }
 ]
}