{
 "title": "tidb source connector",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source_connector_name",
    "query": {
     "query": "label_values(kafka_connect_connector_status{alias=\"acdc/\", connector=~\"source-tidb.*\"}, connector)"
    }
   },
   { "name": "alias", "query": "acdc/" },
   {
    "name": "ticdc_topic_name",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_consumed_total{alias=\"${alias}\",clientId=~\"consumer-${source_connector_name}.*\", topic!=\"\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Runner Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "debezium_metrics_totalreaderrunnercount{alias=\"${alias}\", name=~\"${source_connector_name}.*\"}"
    },
    {
     "expr": "debezium_metrics_alivereaderrunnercount{alias=\"${alias}\", name=~\"${source_connector_name}.*\"}"
    }
   ]
  },
  {
   "title": "Topic Name",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "<center>\n    <h1>${ticdc_topic_name}<h1>\n</center>"
   },
   "targets": [
    {
     "expr": "group by(topic) (kafka_consumer_fetch_manager_records_consumed_total{alias=\"${alias}\", clientId=~\"consumer-${source_connector_name}.*\", topic!=\"\"})"
    }
   ]
  },
  {
   "title": "Ticdc Message Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (topic_name) (kminion_kafka_topic_high_water_mark_sum{alias=\"kafka/\", topic_name=\"${ticdc_topic_name}\"} - kminion_kafka_topic_low_water_mark_sum{alias=\"kafka/\", topic_name=\"${ticdc_topic_name}\"})",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Ticdc Record Consumed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumer_fetch_manager_records_consumed_total{alias=\"${alias}\", clientId=~\"consumer-${source_connector_name}.*\", topic!=\"\"}[5m])",
     "legendFormat": "clientId: {{ clientId }}"
    }
   ]
  },
  {
   "title": "Ticdc Lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag{alias=\"${alias}\", clientId=~\"consumer-${source_connector_name}.*\"} >= 0",
     "legendFormat": "{{ topic }} : {{ partition }}"
    }
   ]
  }
 ]
}