apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-acdc-rules
  namespace: monitoring
spec:
  groups:
    - name: acdc-connector
      rules:
        - alert: 'Acdc connector task failed'
          annotations:
            message: 'connector: {{ $labels.connector }} 存在异常状态 task 超过 20 分钟'
          expr: kafka_connect_worker_connector_failed_task_count{namespace="acdc"} > 0
          for: 20m
          labels:
            app: cdc
            group: cdc
            severity: critical